"""Phase 6 exit check: export the API contract and verify FR coverage.

Run: python scripts/export_api_collection.py

Writes:
  docs/openapi.json            FastAPI's generated spec
  docs/postman_collection.json Postman v2.1 collection, one request per route
  docs/API_COVERAGE.md         FR-01..FR-09 -> endpoint mapping

Exits non-zero if any functional requirement has no endpoint behind it, so
"the collection covers every FR endpoint" is checked rather than asserted.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from main import app  # noqa: E402

OUT = Path(__file__).resolve().parents[1] / "docs"
BASE_URL = "{{base_url}}"

# srs.md §5. Each FR maps to the endpoint(s) that implement it. A requirement
# with no endpoint is a gap in the API, which is what this script catches.
FR_MAP: dict[str, tuple[str, list[str]]] = {
    "FR-01": ("User Registration and Login", ["POST /auth/register", "POST /auth/login"]),
    "FR-02": ("Task Submission", ["POST /jobs"]),
    "FR-03": ("Follow-Up Questions", ["POST /jobs", "PATCH /jobs/{job_id}/followup"]),
    "FR-04": ("Risk Classification", ["POST /jobs/{job_id}/assess", "GET /assessments/{job_id}"]),
    "FR-05": ("Risk Explanation", ["GET /assessments/{job_id}"]),
    "FR-06": ("Tool and Material Recommendation", ["GET /recommendations/{job_id}"]),
    "FR-07": ("Cost and Time Estimation", ["GET /assessments/{job_id}"]),
    "FR-08": ("Professional Recommendation", ["GET /recommendations/{job_id}"]),
    "FR-09": ("Assessment History", ["GET /jobs", "GET /assessments/{job_id}"]),
}

# Requirements the API deliberately does not fully satisfy yet. Listed so the
# gap is visible in the coverage doc rather than implied by a green check.
KNOWN_GAPS = {
    "FR-02": "No photo upload and no location/budget fields: Job stores "
    "description, category, skill_level, urgency only.",
    "FR-07": "cost/time/difficulty are always null - no estimation engine "
    "exists yet. The field is present in the response shape.",
}


def routes() -> list[tuple[str, str]]:
    out = []
    for r in app.routes:
        path = getattr(r, "path", None)
        methods = getattr(r, "methods", None) or set()
        # Skip FastAPI's own docs plumbing - not part of the product API.
        if not path or path.startswith(("/openapi", "/docs", "/redoc")):
            continue
        for m in sorted(methods - {"HEAD", "OPTIONS"}):
            out.append((m, path))
    return sorted(set(out), key=lambda x: (x[1], x[0]))


def to_postman(spec: dict, live: list[tuple[str, str]]) -> dict:
    items = []
    for method, path in live:
        segments = [s for s in path.strip("/").split("/") if s]
        op = spec.get("paths", {}).get(path, {}).get(method.lower(), {})
        req: dict = {
            "name": op.get("summary") or f"{method} {path}",
            "request": {
                "method": method,
                "header": [{"key": "Content-Type", "value": "application/json"}],
                "url": {
                    "raw": f"{BASE_URL}{path}",
                    "host": [BASE_URL],
                    "path": segments,
                },
                "description": (op.get("description") or "").strip(),
            },
        }
        # Every route except health and auth needs the bearer token.
        if not path.startswith(("/health", "/auth")):
            req["request"]["auth"] = {
                "type": "bearer",
                "bearer": [{"key": "token", "value": "{{access_token}}"}],
            }
        if method in {"POST", "PATCH", "PUT"}:
            req["request"]["body"] = {
                "mode": "raw",
                "raw": "{}",
                "options": {"raw": {"language": "json"}},
            }
        items.append(req)

    return {
        "info": {
            "name": "BuildSafe AI API",
            "description": (
                "Generated by scripts/export_api_collection.py - do not edit by "
                "hand. Set {{base_url}} (e.g. http://localhost:8000) and "
                "{{access_token}} from POST /auth/login."
            ),
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
        },
        "variable": [
            {"key": "base_url", "value": "http://localhost:8000"},
            {"key": "access_token", "value": ""},
        ],
        "item": items,
    }


def main() -> int:
    OUT.mkdir(exist_ok=True)
    spec = app.openapi()
    live = routes()
    live_set = {f"{m} {p}" for m, p in live}

    (OUT / "openapi.json").write_text(json.dumps(spec, indent=2), encoding="utf-8")
    (OUT / "postman_collection.json").write_text(
        json.dumps(to_postman(spec, live), indent=2), encoding="utf-8"
    )

    missing: list[str] = []
    rows = []
    for fr, (name, endpoints) in sorted(FR_MAP.items()):
        absent = [e for e in endpoints if e not in live_set]
        missing += [f"{fr} -> {e}" for e in absent]
        note = KNOWN_GAPS.get(fr, "")
        rows.append(
            f"| {fr} | {name} | {'<br>'.join(f'`{e}`' for e in endpoints)} | "
            f"{'❌ MISSING' if absent else '✅'} | {note} |"
        )

    uncovered = sorted(live_set - {e for _, eps in FR_MAP.values() for e in eps})

    (OUT / "API_COVERAGE.md").write_text(
        f"""# API Coverage — FR-01 to FR-09

Generated by `python scripts/export_api_collection.py`. Do not edit by hand.

Phase 6's exit check is that the collection covers every FR endpoint. That is
verified here rather than asserted: the script exits non-zero if any mapped
endpoint is missing from the running app.

| FR | Requirement | Endpoint(s) | Present | Notes |
|---|---|---|---|---|
{chr(10).join(rows)}

## Endpoints not mapped to an FR

{chr(10).join(f'- `{e}`' for e in uncovered) or '_none_'}

These are infrastructure rather than product requirements (liveness and
readiness probes).

## Error shape

Every 4xx/5xx returns `{{"error": {{"code", "message"}}}}` (rules.md §2).
Validation errors return 422 with field-level detail. Covered by
`tests/test_validation_errors.py` and `tests/test_auth.py`.

## Honest gaps

{chr(10).join(f'- **{k}**: {v}' for k, v in sorted(KNOWN_GAPS.items()))}

These are scope decisions, not defects: the endpoints exist and return the
documented shape, but the underlying data is not yet produced. `prd.md` ranks
FR-07 as Medium priority.
""",
        encoding="utf-8",
    )

    print(f"{len(live)} routes exported")
    for m, p in live:
        print(f"  {m:6s} {p}")
    if missing:
        print(f"\nFR COVERAGE GAPS ({len(missing)}):")
        for m in missing:
            print(f"  - {m}")
        return 1
    print(f"\nAll {len(FR_MAP)} functional requirements have endpoints.")
    print(f"wrote {OUT}/openapi.json, postman_collection.json, API_COVERAGE.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
